services:

  rswt:
    container_name: ${APP_NAME}
    hostname: ${APP_NAME}
    image: kirillkrasin/rswt-vue:${APP_VER}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '${APP_PORT}:80'
    restart: always
    logging:
      options:
        max-size: '10m'
        max-file: '3'